version: "3"
services:
  web:
    image: chat-server
    build: .
    environment:
      - MONGOOSE_URI=mongo:mongodb://mongo:27017/chat
    command: "nodemon"
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
